#ifndef CONNECTED_SENSORS_H
#define CONNECTED_SENSORS_H

#define IR_SENSOR_PIN 9
#define LED_PIN 13
#define BUTTON_1_PIN 15
#define BUTTON_2_PIN 15
#define BUTTON_3_PIN 15
#define BUTTON_4_PIN 15
#define POTENTIOMETER_1_PIN 15
#define POTENTIOMETER_2_PIN 15

#endif // CONNECTED_SENSORS_H