#ifndef DISPLAY_PORTS_H
#define DISPLAY_PORTS_H


#define NOKIA_DISPLAY_RST 3
#define NOKIA_DISPLAY_CE  4
#define NOKIA_DISPLAY_DC  5
#define NOKIA_DISPLAY_DIN 6
#define NOKIA_DISPLAY_CLK 7
#define NOKIA_DISPLAY_LGT 8

#endif // DISPLAY_PORTS_H